# Generated by Django 3.1.5 on 2021-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=64, null=True)),
                ('hash', models.CharField(max_length=64, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('count_of_transactions', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
